# proxypool remote server url. Blank for http://127.0.0.1:8080
server_url:
  - https://example.proxypoolserver.com
# server_url: https://example.proxypoolserver.com/clash/proxies?type=vmess


# For your local server
request: http       # http / https
domain: 127.0.0.1   # default: 127.0.0.1
port: 80            # default: 80

cron_interval: 360       # default: 15  minutes
show_remote_speed: true  # default false

healthcheck_timeout: 5     # default 5
healthcheck_connection: 10 # default 100

speedtest: false          # default false
speed_connection: 5       # default 5
speed_timeout: 10         # default 10
